name: Format Check

on:
  pull_request

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'
          php-extensions: 'json, dom, curl, libxml, mbstring'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run ESLint
        run: npm run lint

      - name: Run Laravel Pint
        run: pint --test
