name: Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: question_maker
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prep Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        run: php artisan test --compact --coverage --min=75
